<?xml version="1.0"?><!--prod-imp.xsl-->
<!--XSLT 1.0 - http://www.CraneSoftwrights.com/training -->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html"/>

<!--  ********  DO NOT EDIT THIS FILE ********  -->
<!--  for backwards compatibility, anc_src.xsl can not be changed -->
<!--  it must also be owned only by mta -->
<!--  if changes are needed, rename and also edit merge2web.pl and Makefile  -->
<!--     with new filename -->
<!--  ********  DO NOT EDIT THIS FILE ********  -->

<!-- here we'll assume we're using indiv. src.xml -->
<xsl:template match="//SOURCE">
<html xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
      xsl:version="1.0">

  <xsl:variable name="TOP" select="document('../obs.xml')"/>
  <head><title>
    <xsl:value-of select="$TOP//OBS/NAME"/>
    CXOANC J<xsl:value-of select="NAME"/>
  </title>
  <link rel="stylesheet" href="../../anchors.css" type="text/css"/>
  </head>
  <body>
  <h1>
    <xsl:value-of select="$TOP//OBS/NAME"/>
    CXOANC J<xsl:value-of select="NAME"/>
  </h1>
  <a href="../..">
    <img src="../../logo_tiny.png" alt="home" align="right"/>
  </a>
  <a href="../../help.html">
    <img src="../../logo_help.png" alt="help" align="right"/>
  </a>
  <br/>
  <table border="0">
  <tr><th></th><th>Chandra</th><th>2MASS</th><th>DSS</th></tr>
  <tr>
    <td>
      <table border="1">
        <tr><td>RA</td>
            <td><xsl:value-of select="RA"/></td></tr>
        <tr><td>Declination</td>
            <td><xsl:value-of select="DEC"/></td></tr>
        <tr><td>Raw counts</td>
            <td><xsl:value-of select="CNTS"/></td></tr>
        <tr><td>Net counts</td>
            <td><xsl:value-of select="NET_CNTS"/></td></tr>
        <tr><td>Off-axis dist.</td>
            <td><xsl:value-of select="OFF_AX"/>"</td></tr>
      </table>
    </td>
    <td>
      <img src="chandra.jpg" width="180"/>
    </td>
    <td>
      <img src="2mass.jpg" width="180"/>
    </td>
    <!--
    <td>
      <img src="dss.jpg" width="280" height="280"/>
    </td>
    -->
  </tr></table>
  <br/><a href="Logs">View processing logs</a><br/>

  <h2><font color="#000099">Chandra Data</font></h2>
  Data files:
  <a href="src_evt.fits">source events</a>
  <a href="bkg_evt.fits">background events</a>

  <xsl:apply-templates select="SPECTRA"/>

  <br/>
  <table border="1" bgcolor="#ffff99">
  <tr>
    <th>Quantiles</th>
    <th>25%</th>
    <th>25% error</th>
    <th>50%</th>
    <th>50% error</th>
    <th>75%</th>
    <th>75% error</th>
  </tr>
  <tr>
    <th>keV</th>
    <td><xsl:value-of select="E25"/></td>
    <td><xsl:value-of select="E25_err"/></td>
    <td><xsl:value-of select="E50"/></td>
    <td><xsl:value-of select="E50_err"/></td>
    <td><xsl:value-of select="E75"/></td>
    <td><xsl:value-of select="E75_err"/></td>
  </tr>
  <tr>
    <th>Q-norm</th>
    <td><xsl:value-of select="Q25"/></td>
    <td><xsl:value-of select="Q25_err"/></td>
    <td><xsl:value-of select="Q50"/></td>
    <td><xsl:value-of select="Q50_err"/></td>
    <td><xsl:value-of select="Q75"/></td>
    <td><xsl:value-of select="Q75_err"/></td>
  </tr>
  </table>

  <br/>
  <table>
    <tr>
      <th><font color="#000099">Raymond-Smith fit</font></th>
      <th><font color="#000099">Raymond-Smith 2 temperature fit</font></th>
      <th><font color="#000099">Raymond-Smith 2 temperature fit2</font></th>
    </tr>
    <tr>
      <td><img src="bbrs.gif"/></td>
      <td><img src="bbrs2.gif"/></td>
      <td><img src="bbrs2a.gif"/></td>
    </tr>
  </table>

  <h3><font color="#000099">Light curve</font></h3>
  <table>
    <tr>
      <td><table border="1" bgcolor="#ffff99" cellpadding="5">
      <tr>
        <th colspan="5">Bayesian Blocks - 95% confidence</th>
      </tr>
      <tr>
        <th>N</th>
        <th>Rate (cnts/ks)</th>
        <th>error</th>
        <th>time (s)</th>
      </tr>
      <xsl:apply-templates select="BBLOCKS/BBLOCKS_SIG/BBLOCKS_N"/>
      </table></td>
      <td><img src="bblocks_plot.gif" width="350"/></td>
    </tr>
  </table>
  <h3><font color="#000099">Multi-wavelength data</font></h3>
  <table>
    <tr>
      <xsl:variable name="IR" select="document('2mass.xml')"/>
      <td><table border="1" bgcolor="#ffff99" cellpadding="5">
        <tr><th colspan="4">IR Counterpart (2MASS)</th></tr>
        <tr><td>RA</td><td>Dec</td><td>offset</td><td>Qual.flags</td></tr>
        <tr><td><xsl:value-of select="$IR//SOURCE/tmass_ra"/></td>
            <td><xsl:value-of select="$IR//SOURCE/tmass_dec"/></td>
            <td><xsl:value-of select="$IR//SOURCE/offset"/></td>
            <td><xsl:value-of select="$IR//SOURCE/Q_f"/></td>
        </tr>
        <tr><th>Band</th><th>Mag.</th><th>Error</th><td></td></tr>
        <tr>
          <td>J</td>
          <td><xsl:value-of select="$IR//SOURCE/j_mag"/></td>
          <td><xsl:value-of select="$IR//SOURCE/j_mag_e"/></td>
          <td></td>
        </tr>
        <tr>
          <td>H</td>
          <td><xsl:value-of select="$IR//SOURCE/h_mag"/></td>
          <td><xsl:value-of select="$IR//SOURCE/h_mag_e"/></td>
          <td></td>
        </tr>
        <tr>
          <td>K</td>
          <td><xsl:value-of select="$IR//SOURCE/k_mag"/></td>
          <td><xsl:value-of select="$IR//SOURCE/k_mag_e"/></td>
          <td></td>
        </tr>
      </table></td>
      <td><table border="1" bgcolor="#ffff99" cellpadding="5">
        <tr><th colspan="3">Spitzer Counterpart (IRAC)</th></tr>
        <tr><td>RA</td><td>Dec</td><td>offset</td></tr>
        <tr><td></td><td></td><td></td></tr>
        <tr><td>Band</td><td>Mag.</td><td>Error</td></tr>
        <tr><td>3.6</td><td></td><td></td></tr>
        <tr><td>4.5</td><td></td><td></td></tr>
        <tr><td>5.8</td><td></td><td></td></tr>
        <tr><td>8.0</td><td></td><td></td></tr>
      </table></td>
      <td><table border="1" bgcolor="#ffff99" cellpadding="5">
        <tr><th colspan="3">Optical Counterpart </th></tr>
        <tr><td>RA</td><td>Dec</td><td>offset</td></tr>
        <tr><td></td><td></td><td></td></tr>
        <tr><td>Band</td><td>Mag.</td><td>Error</td></tr>
        <tr><td>?</td><td></td><td></td></tr>
        <tr><td>?</td><td></td><td></td></tr>
        <tr><td>?</td><td></td><td></td></tr>
      </table></td>
    </tr>
  </table>

  <br/><hr/>Last updated:<xsl:value-of select="//created"/>
  </body>
</html>
</xsl:template>

<xsl:template match="SPECTRA">
  <table border="1">
  <tr>
    <th>Model</th>
    <th>nH (10^22/cm^3)</th>
    <th>nH_error</th>
    <th>kT (keV)</th>
    <th>kT_error</th>
    <th>kT2 (keV)</th>
    <th>kT2_error</th>
    <th>abs. flux (ergs/cm^2/s)</th>
    <th>unabs. flux T1 (ergs/cm^2/s)</th>
    <th>unabs. flux T2 (ergs/cm^2/s)</th>
    <th>reduced chi^2</th>
    <th>DOF</th>
  </tr>
  <xsl:apply-templates select="MODEL[@name='bbrs']"/>
  <xsl:apply-templates select="MODEL[@name='bbrs2']"/>
  <xsl:apply-templates select="MODEL[@name='bbrs2a']"/>
  </table>
</xsl:template>

<xsl:template match="MODEL">
  <tr>
    <td><xsl:value-of select="@name"/></td>
    <td><xsl:value-of select="NH"/></td>
    <td><xsl:value-of select="NH_ERR"/></td>
    <td><xsl:value-of select="KT"/></td>
    <td><xsl:value-of select="KT_ERR"/></td>
    <td><xsl:value-of select="KT2"/></td>
    <td><xsl:value-of select="KT2_ERR"/></td>
    <td><xsl:value-of select="FLUX"/></td>
    <td><xsl:value-of select="KT_FLUX"/></td>
    <td><xsl:value-of select="KT2_FLUX"/></td>
    <td><xsl:value-of select="CHI"/></td>
    <td><xsl:value-of select="DOF"/></td>
  </tr>
</xsl:template>

<xsl:template match="BBLOCKS_N">
  <tr>
    <td><xsl:value-of select="@n"/></td>
    <td><xsl:value-of select="BBLOCKS_RATE"/></td>
    <td><xsl:value-of select="BBLOCKS_ERR"/></td>
    <td><xsl:value-of select="BBLOCKS_DT"/></td>
  </tr>
</xsl:template>
 
</xsl:stylesheet>
